services:
  http-server-projeto-korp:
    build:
      context: ./app
    container_name: http-server-projeto-korp
    networks:
      - korp-network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - korp-network
    restart: unless-stopped

  prometheus:
    build:
      context: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - korp-network
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus

networks:
  korp-network:
    driver: bridge

volumes:
  prometheus_data: